# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fca1d62dcf12e820b617359b39eea059ec9c5a38453a5feb613c2807042d41862b69d9613608f94b7a0cc6f1ee1a3cd47f51f18665860e0e7286275bc306da19

test:
  secret_key_base: 988b97ed9df0684976c50780f9f2d63c663730b0250eb6d4d2101568aca9711304cf6a1a56d3f9d816532054a0f09dfc3db12ea767761b368a3262ece2836ee0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
